---
title: "Welcome to My Site"
description: "This is a Quarto Website"
author: "Matteo Aldovardi"
date: 09/11/2024
format:
  html:
    theme: slate
---

::: {#headbar layout-ncol=1}
![Image generated using DALL·E 3 with the following prompt " Generate an image of a woman painting while sitting on a porch. The painting style should evoke the aesthetics of Dante Gabriel Rossetti and Raffaello, with a focus on rich, detailed, and romantic elements. The porch is surrounded by the vibrant, warm colors of an autumn landscape in Connecticut, featuring golden and red foliage. The overall atmosphere should feel serene and artistic, blending natural beauty with classical, Renaissance-inspired art. "](images/banner.jpeg){width=100% height=300px}
:::

# Purpose of This Site

Hello! I'm Matteo Aldovardi, a dedicated machine learning enthusiast and mathematician. This site serves as my personal blog and portfolio, where I document my exploration of data science, AI, and mathematics, sharing insights, projects, and my learning journey along the way. Check out my [portfolio](portfolio.qmd) for projects and examples of my work, or visit my [blog](blog.qmd) for insights and updates on my latest explorations.


## Recent Posts
  - [Training and Visualizing a PPO Agent on CartPole using Stable Baselines3](blog/post_18-09-24.qmd)

  - [Implementing K-Nearest Neighbor with Python](blog/post_11-09-24.qmd)